version: '3.5'
services:
  postgresql:
    container_name: postgresql
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=nasdaq
      - APP_DB_PASS=password
      - APP_DB_NAME=gorm
    volumes:
    - ./db:/docker-entrypoint-initdb.d/
    networks:
      - backend-bridge
    restart: always
  redis:
    container_name: redis
    image: redis:latest
    ports:
    - "6379:6379"
    networks:
      - backend-bridge
    restart: always
  nas_service:
    container_name: nas_service
    ports:
      - "8080:8080"
    build:
      context: ./
      dockerfile: Dockerfile
    command: ./main
    restart: always
    networks:
      - backend-bridge
    depends_on:
      - postgresql
      - redis

networks:
  backend-bridge:
    driver: bridge
