definitions:
  controller.Login:
    properties:
      account:
        type: string
      password:
        type: string
    required:
    - account
    - password
    type: object
  controller.Register:
    properties:
      account:
        type: string
      email:
        type: string
      password:
        type: string
    required:
    - account
    - email
    - password
    type: object
host: localhost:8080
info:
  contact:
    name: Flynn Sun
  description: Gin swagger
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin swagger
  version: "1.0"
paths:
  /users/{id}:
    get:
      parameters:
      - default: 1
        description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - users
  /users/login/:
    post:
      parameters:
      - description: JSON data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - users
  /users/register/:
    post:
      parameters:
      - description: JSON data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.Register'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - users
swagger: "2.0"
