definitions:
  controller.Login:
    properties:
      account:
        example: "000"
        type: string
      password:
        example: "000"
        type: string
    required:
    - account
    - password
    type: object
  controller.Register:
    properties:
      account:
        example: account
        type: string
      email:
        example: test123@gmail.com
        type: string
      password:
        example: password
        type: string
    required:
    - account
    - email
    - password
    type: object
  controller.RegisterResponse:
    properties:
      data:
        type: string
      msg:
        example: Successfully login.
        type: string
      status:
        example: 0
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    name: Flynn Sun
  description: Gin swagger
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin swagger
  version: "1.0"
paths:
  /users/auth/{id}:
    get:
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - default: 1
        description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - users
  /users/login/:
    post:
      parameters:
      - description: JSON data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - users
  /users/register/:
    post:
      parameters:
      - description: register
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/controller.Register'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controller.RegisterResponse'
            type: array
      tags:
      - users
swagger: "2.0"
